name: Publish to NPM

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs: 
  integrity: 
    runs-on: ${{ matrix.os }}

    strategy: 
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

  publish: 
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [integrity]
    steps:
      - uses: actions/checkout@v4
      - name: USe node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm run publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    