name: Publish to NPM

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs: 
  integrity: 
    runs-on: ${{ matrix.os }}

    strategy: 
      matrix:
        node-version: [20]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test